import { faCloudversify } from '@fortawesome/free-brands-svg-icons';
import { faAnglesUp, faAngleUp, faBars, faBarsStaggered, faCalculator, faCamera, faCaretLeft, faCaretRight, faCheck, faCircleNotch, faCloudArrowUp, faFireBurner, faHeart, faHome, faHurricane, faLanguage, faMinus, faO, faPen, faPenAlt, faPepperHot, faPlus, faPrint, faQuoteLeft, faQuoteRight, faRotateLeft, faSearch, faShare, faTriangleExclamation, faTurnDown, faUnlockKeyhole, faUser, faX } from '@fortawesome/free-solid-svg-icons';
import { faClock, faFaceSadCry, faFaceSadTear } from '@fortawesome/free-regular-svg-icons';

export const IconLib = {
    accountNone: faUser,
    account: faUser,
    ailocalized: faLanguage,
    attention: faTriangleExclamation,
    calc: faCalculator,
    calcMinus: faMinus,
    calcPlus: faPlus,
    camera: faCamera,
    caretLeft: faCaretLeft,
    caretRight: faCaretRight,
    clock: faClock,
    difficulty: {
        0: faO,
        1: faMinus,
        2: faAngleUp,
        3: faAnglesUp,
    },
    edit: faPen,
    goDownToArrow: faTurnDown,
    home: faHome,
    ingredients: faPepperHot,
    like: faHeart,
    login: faUnlockKeyhole,
    menu: faBars,
    menuOpened: faBarsStaggered,
    nextcloud: faCloudversify,
    preparation: faFireBurner,
    print: faPrint,
    quote: faQuoteRight,
    recipeNew: faPlus,
    reset: faRotateLeft,
    sadFace: faFaceSadTear,
    search: faSearch,
    searchClose: faX,
    searchStart: faCheck,
    share: faShare,
    spinner: faCircleNotch,
    upload: faCloudArrowUp,
};