import { faCloudversify } from '@fortawesome/free-brands-svg-icons';
import { faClock, faFaceSadTear, faSquare, faSquareCheck } from '@fortawesome/free-regular-svg-icons';
import { faAnglesUp, faAngleUp, faBars, faBarsStaggered, faBook, faBookAtlas, faBookOpen, faCalculator, faCamera, faCaretLeft, faCaretRight, faCheck, faCircleNotch, faCirclePlus, faCloudArrowUp, faFireBurner, faFloppyDisk, faHeart, faHome, faInfoCircle, faLanguage, faMinus, faO, faPen, faPepperHot, faPlus, faPrint, faQuoteRight, faRotateLeft, faSearch, faShare, faTriangleExclamation, faTurnDown, faUnlockKeyhole, faUser, faX } from '@fortawesome/free-solid-svg-icons';

export const IconLib = {
    accountNone: faUser,
    account: faUser,
    ailocalized: faLanguage,
    attention: faTriangleExclamation,
    boxCheck: faSquareCheck,
    boxUncheck: faSquare,
    calc: faCalculator,
    calcMinus: faMinus,
    calcPlus: faPlus,
    camera: faCamera,
    caretLeft: faCaretLeft,
    caretRight: faCaretRight,
    clock: faClock,
    collection: faBookOpen,
    collectionNew: faPlus,
    difficulty: {
        0: faO,
        1: faMinus,
        2: faAngleUp,
        3: faAnglesUp,
    },
    edit: faPen,
    goDownToArrow: faTurnDown,
    home: faHome,
    info: faInfoCircle,
    ingredients: faPepperHot,
    like: faHeart,
    login: faUnlockKeyhole,
    menu: faBars,
    menuOpened: faBarsStaggered,
    nextcloud: faCloudversify,
    preparation: faFireBurner,
    print: faPrint,
    quote: faQuoteRight,
    recipeNew: faPlus,
    reset: faRotateLeft,
    sadFace: faFaceSadTear,
    save: faFloppyDisk,
    search: faSearch,
    searchClose: faX,
    searchStart: faCheck,
    share: faShare,
    spinner: faCircleNotch,
    upload: faCloudArrowUp,
};