[package]
name = "kochbuch"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"                                  # Web framework
serde = { version = "1", features = ["derive"] } # Serialization/Deserialization
serde_json = "1"                                 # JSON handling
